// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YourHike.Models;

namespace YourHike.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201129113219_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-rc.2.20475.6");

            modelBuilder.Entity("YourHike.Models.DTO.FileDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileType")
                        .HasColumnType("TEXT");

                    b.Property<int>("HikeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HikeId");

                    b.ToTable("Files");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "Zdjęcie pierwsze",
                            FileName = "pierwsze_zdjecie.png",
                            FileType = "png",
                            HikeId = 1,
                            UploadTime = new DateTime(2020, 11, 29, 12, 32, 18, 986, DateTimeKind.Local).AddTicks(7110)
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "Zdjęcie drugie",
                            FileName = "drugie_zdjecie.png",
                            FileType = "png",
                            HikeId = 1,
                            UploadTime = new DateTime(2020, 11, 29, 12, 32, 18, 986, DateTimeKind.Local).AddTicks(8043)
                        },
                        new
                        {
                            Id = 3,
                            DisplayName = "Zdjęcie trzecie",
                            FileName = "trzecie_zdjecie.png",
                            FileType = "png",
                            HikeId = 2,
                            UploadTime = new DateTime(2020, 11, 29, 12, 32, 18, 986, DateTimeKind.Local).AddTicks(8079)
                        });
                });

            modelBuilder.Entity("YourHike.Models.DTO.HikeDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Distance")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndPlace")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartPlace")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Hikes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Distance = 5.4000000000000004,
                            EndDate = new DateTime(2020, 11, 30, 12, 32, 18, 984, DateTimeKind.Local).AddTicks(4982),
                            EndPlace = "Las Kabacki",
                            StartDate = new DateTime(2020, 11, 29, 12, 32, 18, 979, DateTimeKind.Local).AddTicks(8797),
                            StartPlace = "Dom",
                            Title = "Las Kabacki"
                        },
                        new
                        {
                            Id = 2,
                            Distance = 9.1999999999999993,
                            EndDate = new DateTime(2020, 12, 4, 12, 32, 18, 984, DateTimeKind.Local).AddTicks(7892),
                            EndPlace = "Chojnowski Park Krajobrazowy",
                            StartDate = new DateTime(2020, 12, 4, 12, 32, 18, 984, DateTimeKind.Local).AddTicks(7853),
                            StartPlace = "Dom",
                            Title = "Chojnowski Park Krajobrazowy"
                        });
                });

            modelBuilder.Entity("YourHike.Models.DTO.HistoryHikeDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("HikeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifyTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HikeId");

                    b.ToTable("HikesHistory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Zmiana tytułu",
                            HikeId = 1,
                            ModifyTime = new DateTime(2020, 11, 29, 12, 32, 18, 987, DateTimeKind.Local).AddTicks(432),
                            NewValue = "Chojnowski Park Krajobrazowy",
                            OldValue = "Chojnowski"
                        });
                });

            modelBuilder.Entity("YourHike.Models.DTO.FileDTO", b =>
                {
                    b.HasOne("YourHike.Models.DTO.HikeDTO", "Hike")
                        .WithMany("Files")
                        .HasForeignKey("HikeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hike");
                });

            modelBuilder.Entity("YourHike.Models.DTO.HistoryHikeDTO", b =>
                {
                    b.HasOne("YourHike.Models.DTO.HistoryHikeDTO", "Hike")
                        .WithMany()
                        .HasForeignKey("HikeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hike");
                });

            modelBuilder.Entity("YourHike.Models.DTO.HikeDTO", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
