// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YourHike.Models;

namespace YourHike.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201026165548_ModelChanges")]
    partial class ModelChanges
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-rc.2.20475.6");

            modelBuilder.Entity("YourHike.Models.DTO.HikeDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Distance")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndPlace")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartPlace")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Hikes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Distance = 5.4000000000000004,
                            EndDate = new DateTime(2020, 10, 27, 17, 55, 48, 22, DateTimeKind.Local).AddTicks(1197),
                            EndPlace = "Las Kabacki",
                            StartDate = new DateTime(2020, 10, 26, 17, 55, 48, 18, DateTimeKind.Local).AddTicks(130),
                            StartPlace = "Dom",
                            Title = "Las Kabacki"
                        },
                        new
                        {
                            Id = 2,
                            Distance = 9.1999999999999993,
                            EndDate = new DateTime(2020, 10, 31, 17, 55, 48, 22, DateTimeKind.Local).AddTicks(4252),
                            EndPlace = "Chojnowski Park Krajobrazowy",
                            StartDate = new DateTime(2020, 10, 31, 17, 55, 48, 22, DateTimeKind.Local).AddTicks(4197),
                            StartPlace = "Dom",
                            Title = "Chojnowski Park Krajobrazowy"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
