// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YourHike.Models;

namespace YourHike.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-rc.2.20475.6");

            modelBuilder.Entity("YourHike.Models.DTO.HikeDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Distance")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndPlace")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartPlace")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Hiks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Distance = 5.4000000000000004,
                            EndDate = new DateTime(2020, 10, 26, 19, 53, 13, 14, DateTimeKind.Local).AddTicks(7356),
                            EndPlace = "Las Kabacki",
                            StartDate = new DateTime(2020, 10, 25, 19, 53, 13, 10, DateTimeKind.Local).AddTicks(6347),
                            StartPlace = "Dom",
                            Title = "Las Kabacki"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
